# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1024)),
                ('ref', models.IntegerField()),
                ('ctime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
