# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
