# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170722_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
