"""empty message

Revision ID: 9cc7602d1c67
Revises: 981e781ee0b7
Create Date: 2018-12-27 21:45:00.736196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc7602d1c67'
down_revision = '981e781ee0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base64', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pics')
    # ### end Alembic commands ###
